[DEFAULT]
# Router settings
method = phantom

# Patient settings
[PatientConfig]
plan_dir = DICOM_PLAN
ct_dir = CT_SET
cbct_dir = IMAGES
export_structures = bowel,rectum,bladder
priority = 1, 2, 3
cm_mask = bowel
image_modality = XVI 

#phantom settings
phantom_path = test/test_data/phantom/phantom.mha
intensity_factor = 1.0
water_threshold = 300.0
enhancement_factor = 4.0
lower_threshold = -600.0
body_threshold = -200.0
gaussian_sigma = 2.0
noise_range_min = -35.0
noise_range_max = 35.0

