[DEFAULT]
method=standard

[PatientConfig]
plan_dir = .
ct_dir = .
cbct_dir = .
export_structures = lung_l,lung_r,heart,liver,esophagus,spinal_cord
priority = 1,2,3,4,5,6
image_modality = synrad2025
use_totalsegmentator = True


[MotionConfig]
motion_type = THORAX
amplitude_breathing =90
amplitude_heart = 20
frequency_breathing = 20
frequency_heartbeat = 70
#breaths per minute (12-20)
time_per_projection = 0.18
#seconds
uncertainty = 0.2
#seconds

[PhysicsConfig]
# X-ray physics parameters
# photon_flux = 4.16e5
spr = 1.6
mas = 0.4
kv = 100
saturation_factor = 2.0
bp_amplitude = 1.07
bp_std = 522.0
# Execution parameters - don't change unless needed
threads = 8
max_block_index = 200

[GeometryConfig]
# CBCT geometry - default values for classical Elekta XVI setup
source_origin_distance = 1000.
source_detector_distance = 1536.
detector_offset = 0.0
# Detector specifications
detector_size_h = 409.6
detector_size_w = 409.6
detector_pixels_h = 512
detector_pixels_w = 512
# Acquisition angles
start_angle = 0.0
end_angle = 360.0
angle_increments = 0.54545

[ReconstructionVolumeConfig]
# Reconstruction volume specifications
recon_size = 410,66,410
recon_origin = -204.5,-130.0,-204.5
recon_spacing = 1.0,4.0,1.0
